version: '3-8'

services:
  dmondragon:
    build:
      context: .
      dockerfile: Dockerfile
    image: dmondragon
    container_name: dmondragon
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "11303:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network-mondragon
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js


  db:
    image: mongo
    container_name: db_dmondragon
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:     
      - dbdata-mondragon:/data/db
    networks:
      - app-network-mondragon
networks:
    app-network-mondragon:
        driver: bridge

volumes:
    dbdata-mondragon:
    node_modules: 
